analysis_name: 50NiTiSC_0D_1_mono_98_redo_thresh1 # defaults to analysis

## working directory defaults to current working directory
## all relative paths specified herein are assumed to be in the working_dir
## any files not in working_dir should be specified with an absolute path
#working_dir: 

multiprocessing: -1 # "all", or "half", or -1 means all but one, defaults to -1

material:
  definitions: material_niti
  active: NiTi_mono

image_series:
  file:
    stem: /media/DIFFRACTION/CHESS/2015_Dec/50NiTiSC_0D_1/98/ff/ff_%05d.ge2 # can include relative or absolute path
    ids: [845] # or can use globs: ["*2[4-9]"]
  images:
    start: 1
    stop: 3600
    step: 1
  omega:
    start: 0.0
    step: 0.1
    stop: 360.0
  dark: /media/DIFFRACTION/CHESS/2015_Dec/50NiTiSC_0D_1/99/ff/ff_00860.ge2
  flip: h # ~, v, h, hv, vh, cw, ccw

instrument:
  parameters: ge_detector.yml
  detector: # this section is only needed to convert old files to the new spec
    parameters_old: detector_55p618_avg_CHESS_15_dec_APS_cal # the old detector spec, produced by the GUI
    pixels: # this section required to convert from old detector spec
      rows: 2048
      columns: 2048
      size: [0.200, 0.200] # [row height, col width] mm

# Forward modeling module: Generate synthetic microstructure data (X, Y, Z, material, orientation, strain)
# or read microstructure data from user and synthesize simulated diffraction patterns (X, Y, Omega in TXT and GE2 files)
forward_modeling:
  modeling_mode: fwdmodel              # datagen OR fwdmodel. datagen generates random NiTi_cubic data. fwdmodel does actual fwd modeling
  datagen:
    number_of_points: 1000000          # Number of microstructure points to generate (1000 is fast, 1M is 10 minutes)
    output_file_name: ms-data-test.csv # Output file name for syntheric microstructural data generated 
  input_file_name: ms-data-test.csv    # Input file from which X, Y, Z, material, orientation and strain info is read for fwdmodel
  output_file_name: synth-data.out     # TXT file to which X, Y, Omega for synth spots is written for fwdmodel
  output_ge: false                     # Write GE2 data or not
  output_ge_name: ff_synth_00000.ge2   # GE2 file name
  output_omega:                        # Omega stepping in the GE2 file for fwdmodel
    start: 0.0
    step: 0.1
    stop: 360.0

# GE2 pre-processing (or spot clean-up) module. Obtain spot local maxima, spot size and shape.
pre_processing:
  ge_reader_threshold: 50        # Anything less than this will be set to zero on reading GE2 file
  min_blob_size: 125             # Blob containing less than these pixels will be discarded
  min_peak_separation: 5         # Minimum separation between local maxima
  print_spots_info: true         # Print omega, x, y and intensity for the local maxima found
  print_ge: true                 # If true, GE2 files will be written to disk (pretty slow for now)
  print_diag_images: false       # Print diagnostic PNGs with local maxima overlaid on intensity etc
  radius_gray_dilation_omega: 1  # When writing GE2 files, spot will be dilated by these pixels in omega
  radius_gray_dilation_x: 4      # When writing GE2 files, spot will be dilated by these pixels in x 
  radius_gray_dilation_y: 8      # When writing GE2 files, spot will be dilated by these pixels in y

find_orientations:
  orientation_maps:
    # A file name must be specified. If it doesn't exist, one will be created
    file: eta-omega.cpl

    threshold: 15
    #bin_frames: 1 # defaults to 1

    ## "all", or a list of hkl orders used to find orientations
    ## defaults to all orders listed in the material definition
    active_hkls: [0,1,2]

  ## either search full quaternian grid, or seed search based on sparse
  ## orientation maps
  #use_quaternian_grid: some/file/name # defaults to seeded search
  seed_search: # this section is ignored if use_quaternian_grid is defined
    hkl_seeds: [0,1] # hkls ids to use, must be defined for seeded search
    fiber_step: 0.5 # degrees, defaults to ome tolerance

  threshold: 1

  omega:
    tolerance: 0.5 # in degrees, defaults to 2x ome step

  ## specify the branch cut, in degrees. The range must be 360 degrees.
  ## defaults to ["image_series:omega:start", "image_series:omega:start"+-360]
  ## depending on sign of "image_series:omega:step"
  period: [0.0, 360.0] # in degrees, defaults to full 360 starting at "ome start"

  eta:
    tolerance: 0.5 # in degrees, defaults to 2x ome step
    mask: 5 # degrees, mask angles close to ome rotation axis, defaults to 5

  clustering:
    radius: 0.5
    completeness: 0.8 # completeness threshold
    algorithm: fclusterdata # defaults to dbscan

  #extract_measured_g_vectors: true # defaults to false

fit_grains:
  do_fit: true # if false, extracts grains but doesn't fit. defaults to true

  #estimate: FePd_d_8/grains.out # defaults to None

  #npdiv: 1 # number of polar pixel grid subdivisions, defaults to 2

  panel_buffer: 10 # don't fit spots within this many pixels from edge

  threshold: 15

  tolerance:
    tth: [0.1, 0.1] # tolerance lists must be identical length
    eta: [2.0, 2.0]
    omega: [2.0, 2.0]

  tth_max: 15 # true, false, or a non-negative value, defaults to true
